### ISSUE TITLE
关于综述

### ISSUE THREAD

**Issue by muzi-Lu** [siyandong/awesome-visual-localization#3]
作者您好，想问一下有没有关于视觉定位这方面的综述性文章？

**Comment by CherryXChen** [comment]
A Critical Analysis of Image-based Camera Pose Estimation Techniques

**Comment by muzi-Lu** [comment]
谢谢您

**Comment by siyandong** [comment]
论文列表目前整理的还不够全面，欢迎大家把落下的相关论文加入进来
